### ISSUE TITLE
Условная компиляция для Vector3D

### ISSUE THREAD

**Issue by avasyukov** [tungstencucumber/linal#2]
Вероятно, просто забыта

**Comment by tungstencucumber** [comment]
Строк
`#ifndef VECTOR3D_H
#define VECTOR3D_H
...
#endif`
недостаточно, нужно что-то ещё?

**Comment by tungstencucumber** [comment]
И да, как сделать так, чтобы вставляемый в этих сообщениях код правильно табулировался?

**Comment by avasyukov** [comment]
Пардон. Всё на месте. Мой косяк.

// Про форматирование кода - там кнопка такая на панельке есть "Insert code".

**Comment by tungstencucumber** [comment]
Да, insert code. Я воспользовался ей в сообщении выше, но она забила на все переносы строки.
