### ISSUE TITLE
Подчистка репозитория

### ISSUE THREAD

**Issue by avasyukov** [tungstencucumber/linal#3]
Заливать в репозиторий папку build/ не стоит - в ней временные файлы, бинарники и т.д. В репозитории только исходники и сценарий сборки.

**Comment by tungstencucumber** [comment]
То есть конечный бинарник тоже не надо заливать?

**Comment by avasyukov** [comment]
Не надо. В репозитории лежат исходники и сценарий сборки, по которому получается бинарник.

(А конкретный бинарник к тому же собран под конкретную операционку и архитектуру CPU. То есть на соседнем компьютере он банально не запустится.)
